title: Geforce-Kepler-patcher
description: For macOS Monterey with Graphics cards based on Kepler architecture.
github:
  repository_url: https://github.com/chris1111/Geforce-Kepler-patcher
remote_theme: chris1111/cayman-dark
